export default {
  id: "2024-symmetry",
  year: 2024,
  title: "The Algebra and Calculus of Stochastically Perturbed Spacetime with Classical and Quantum Applications",
  shortTitle: "Stochastic Spacetime",
  author: "Dragana Pilipovi\u0107",
  affiliation: "Department of Physics, University of Illinois Chicago",
  journal: "Symmetry",
  volume: "16, 36",
  date: "28 December 2023",
  doi: "10.3390/sym16010036",
  url: "https://doi.org/10.3390/sym16010036",
  abstract: `We consider an alternative to dark matter: the addition of stochastic perturbations to spacetime to enforce a minimum length and establish a fundamental uncertainty at minimum length scale. We derive the generators of rotations and boosts, along with the connection, for stochastically perturbed spacetime. ML spacetime preserves the metric, the directional derivative, and the canonical commutator. As an application, we consider galaxy rotation curves to find that rotational velocity becomes constant at large distances from the center of the galaxy.`,
  hasJourney: false,
  paramLabel: "R (kpc)",
  paramMin: 1,
  paramMax: 120,
  paramDefault: 40,
  paramStep: 1,
};
