export default {
  id: "2023-hubble",
  year: 2023,
  title: "Late-time dark energy and Hubble tension",
  shortTitle: "Hubble Tension",
  author: "Dragana Pilipovi\u0107",
  affiliation: "Department of Physics, University of Illinois Chicago",
  journal: "Open Astronomy",
  volume: "32, 20220221",
  date: "13 April 2023",
  doi: "10.1515/astro-2022-0221",
  url: "https://doi.org/10.1515/astro-2022-0221",
  abstract: `We extend Einstein's theory of general relativity by introducing stochastic elements and apply it to explore late-time redshift. The stochastic perturbation of spacetime enforces an effective minimum length to give us a cosmological constant naturally derived from the diffusive nature of spacetime and a redshift driven by both geometry and diffusion. "Dark energy" is the manifestation of fundamental uncertainty caused by minimum length of spacetime. The theory suggests that the Hubble tension might be relieved by the diffusive character of spacetime.`,
  hasJourney: false,
  paramLabel: "f = -q",
  paramMin: 0.5,
  paramMax: 1.1,
  paramDefault: 0.95,
  paramStep: 0.005,
};
