export default {
  id: "2024-universe",
  year: 2024,
  title: "An Infinitely Old Universe with Planck Fields Before and After the Big Bang",
  shortTitle: "Infinitely Old Universe",
  author: "Dragana Pilipovi\u0107",
  affiliation: "Department of Physics, University of Illinois Chicago",
  journal: "Universe",
  volume: "10, 400",
  date: "17 October 2024",
  doi: "10.3390/universe10100400",
  url: "https://doi.org/10.3390/universe10100400",
  abstract: `The Robertson\u2013Walker minimum length (RWML) theory considers stochastically perturbed spacetime to describe an expanding universe governed by geometry and diffusion. We explore the possibility of static, torsionless universe eras with conserved energy density. We find that the RWML theory provides asymptotically static equations of state under positive curvature both far in the past and far into the future, with a Big Bang singularity in between.`,
  hasJourney: false,
  paramLabel: "X = D/H",
  paramMin: 0.01,
  paramMax: 10,
  paramDefault: 2.0,
  paramStep: 0.01,
};
