import { R_MIN, R_H, R_T, R_0, R_A } from "../physics.js";
import Eq from "@/shared/Eq.jsx";
import HoverTerm from "@/shared/HoverTerm.jsx";
import { TERMS } from "../highlight.js";
import { colors, rgba, fonts, styles } from "@/theme.js";

export default function Framework() {
  return (
    <section style={styles.section}>
      <h2 style={styles.heading}>2. Stochastic Spacetime Framework</h2>

      <p style={styles.prose}>
        Each point in spacetime carries a Planck-scale uncertainty generated by
        a stochastic field <Eq tex="\sigma" />. The transition to spherical
        coordinates folds spacetime onto itself, revealing nonzero perturbation
        correlations near <Eq tex="r \approx 0" /> and a nonzero VEV in radial
        perturbations. An effective Schwarzschild geometry emerges — entirely a
        statistical structure, not curvature from the Einstein equations.
      </p>

      <Eq display num="8" tex={`
        \\frac{dt}{dr} = \\frac{1}{1 - \\frac{\\sigma^2}{2r}}
      `} />

      <p style={styles.prose}>
        The Schwarzschild radius at the Planck scale
        is <Eq tex="r_0 = \\frac{\\sigma^2}{2}" />, and five critical radii
        emerge from minimizing the scalar field potential:
      </p>

      <table style={styles.table}>
        <thead>
          <tr>
            <th style={th}>Symbol</th>
            <th style={th}>Value</th>
            <th style={th}>Meaning</th>
          </tr>
        </thead>
        <tbody>
          {[
            ["r_{\\min}", `\\sqrt{3/8}\\,r_0 \\approx ${R_MIN.toFixed(3)}\\,r_0`, "Minimum physical radius", null],
            ["r_h", `\\sqrt{5-\\sqrt{21}}\\,r_0 \\approx ${R_H.toFixed(3)}\\,r_0`, "Deep well minimum", TERMS.rh],
            ["r_T", `\\sqrt{7/8}\\,r_0 \\approx ${R_T.toFixed(3)}\\,r_0`, "Transition point", null],
            ["r_0", "1.000\\,r_0", "Schwarzschild radius", TERMS.r0],
            ["r_a", `\\sqrt{5+\\sqrt{21}}\\,r_0 \\approx ${R_A.toFixed(2)}\\,r_0`, "Accretion disk", TERMS.ra],
          ].map(([sym, val, meaning, term]) => (
            <tr key={sym}>
              <td style={td}>
                {term
                  ? <HoverTerm term={term}><Eq tex={sym} /></HoverTerm>
                  : <Eq tex={sym} />}
              </td>
              <td style={td}><Eq tex={val} /></td>
              <td style={{ ...td, color: "rgba(200,210,220,0.6)" }}>{meaning}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

const th = { ...styles.th, textAlign: "left", letterSpacing: 1, textTransform: "uppercase" };
const td = { ...styles.td, fontFamily: fonts.mono, fontSize: 13, color: "rgba(200,210,220,0.8)" };
