import { R_MIN, R_H, R_T, R_0, R_A } from "../physics.js";
import Eq from "./Eq.jsx";

export default function Framework() {
  return (
    <section style={section}>
      <h2 style={heading}>2. Stochastic Spacetime Framework</h2>

      <p style={prose}>
        Each point in spacetime carries a Planck-scale uncertainty generated by
        a stochastic field <Eq tex="\sigma" />. The transition to spherical
        coordinates folds spacetime onto itself, revealing nonzero perturbation
        correlations near <Eq tex="r \approx 0" /> and a nonzero VEV in radial
        perturbations. An effective Schwarzschild geometry emerges — entirely a
        statistical structure, not curvature from the Einstein equations.
      </p>

      <Eq display num="8" tex={`
        \\frac{dt}{dr} = \\frac{1}{1 - \\frac{\\sigma^2}{2r}}
      `} />

      <p style={prose}>
        The Schwarzschild radius at the Planck scale
        is <Eq tex="r_0 = \\frac{\\sigma^2}{2}" />, and five critical radii
        emerge from minimizing the scalar field potential:
      </p>

      <table style={table}>
        <thead>
          <tr>
            <th style={th}>Symbol</th>
            <th style={th}>Value</th>
            <th style={th}>Meaning</th>
          </tr>
        </thead>
        <tbody>
          {[
            ["r_{\\min}", `\\sqrt{3/8}\\,r_0 \\approx ${R_MIN.toFixed(3)}\\,r_0`, "Minimum physical radius"],
            ["r_h", `\\sqrt{5-\\sqrt{21}}\\,r_0 \\approx ${R_H.toFixed(3)}\\,r_0`, "Deep well minimum"],
            ["r_T", `\\sqrt{7/8}\\,r_0 \\approx ${R_T.toFixed(3)}\\,r_0`, "Transition point"],
            ["r_0", "1.000\\,r_0", "Schwarzschild radius"],
            ["r_a", `\\sqrt{5+\\sqrt{21}}\\,r_0 \\approx ${R_A.toFixed(2)}\\,r_0`, "Accretion disk"],
          ].map(([sym, val, meaning]) => (
            <tr key={sym}>
              <td style={td}><Eq tex={sym} /></td>
              <td style={td}><Eq tex={val} /></td>
              <td style={{ ...td, color: "rgba(200,210,220,0.6)" }}>{meaning}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}

const section = { maxWidth: 740, margin: "0 auto", padding: "40px 32px" };
const heading = { fontSize: 22, fontWeight: 400, marginBottom: 16, color: "#e0e8f0" };
const prose = { fontSize: 16, fontWeight: 300, lineHeight: 1.8, color: "rgba(200,210,220,0.75)", margin: "16px 0" };
const table = { width: "100%", borderCollapse: "collapse", margin: "20px 0" };
const th = { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, color: "rgba(0,212,255,0.5)", textAlign: "left", padding: "8px 12px", borderBottom: "1px solid rgba(0,212,255,0.1)", letterSpacing: 1, textTransform: "uppercase" };
const td = { fontFamily: "'IBM Plex Mono', monospace", fontSize: 13, padding: "8px 12px", borderBottom: "1px solid rgba(0,212,255,0.05)", color: "rgba(200,210,220,0.8)" };
